export type Category = "matematica" | "abstracto" | "espacial"

export interface Question {
  question: string
  options: string[]
  correctAnswer: number
  hint?: string
  image?: string
}

export const questions: Record<Category, Question[]> = {
  matematica: [
    // Secuencias numéricas básicas (1-20)
    {
      question: "¿Cuál es el siguiente número en la secuencia? 2, 4, 8, 16, 32, __",
      options: ["48", "64", "56", "72"],
      correctAnswer: 1,
      hint: "Cada número es el doble del anterior",
    },
    {
      question: "Completa la serie: 1, 1, 2, 3, 5, 8, 13, __",
      options: ["18", "21", "19", "20"],
      correctAnswer: 1,
      hint: "Suma los dos números anteriores (Serie de Fibonacci)",
    },
    {
      question: "¿Qué número continúa? 3, 6, 12, 24, 48, __",
      options: ["72", "96", "84", "64"],
      correctAnswer: 1,
      hint: "Cada número se multiplica por 2",
    },
    {
      question: "Serie: 100, 95, 90, 85, 80, __",
      options: ["75", "70", "78", "72"],
      correctAnswer: 0,
      hint: "Se resta 5 cada vez",
    },
    {
      question: "¿Siguiente número? 2, 6, 12, 20, 30, __",
      options: ["40", "42", "38", "44"],
      correctAnswer: 1,
      hint: "Diferencias: +4, +6, +8, +10, +12",
    },
    {
      question: "Serie: 1, 4, 9, 16, 25, __",
      options: ["30", "35", "36", "32"],
      correctAnswer: 2,
      hint: "Números al cuadrado: 1², 2², 3², 4², 5², 6²",
    },
    {
      question: "¿Qué sigue? 5, 10, 20, 40, 80, __",
      options: ["120", "160", "140", "100"],
      correctAnswer: 1,
      hint: "Multiplicar por 2 cada vez",
    },
    {
      question: "Serie: 1, 3, 7, 15, 31, __",
      options: ["47", "55", "63", "59"],
      correctAnswer: 2,
      hint: "Patrón: (n × 2) + 1",
    },
    {
      question: "Serie: 2, 5, 11, 23, 47, __",
      options: ["71", "83", "95", "99"],
      correctAnswer: 2,
      hint: "Patrón: (n × 2) + 1",
    },
    {
      question: "¿Qué sigue? 1, 2, 4, 7, 11, 16, __",
      options: ["20", "21", "22", "23"],
      correctAnswer: 2,
      hint: "Diferencias: +1, +2, +3, +4, +5, +6",
    },
    {
      question: "Serie: 81, 27, 9, 3, __",
      options: ["2", "1", "0", "1.5"],
      correctAnswer: 1,
      hint: "Divide entre 3 cada vez",
    },
    {
      question: "¿Siguiente? 7, 14, 28, 56, 112, __",
      options: ["168", "196", "224", "240"],
      correctAnswer: 2,
      hint: "Multiplica por 2",
    },
    {
      question: "Serie: 1, 8, 27, 64, 125, __",
      options: ["180", "196", "216", "225"],
      correctAnswer: 2,
      hint: "Cubos: 1³, 2³, 3³, 4³, 5³, 6³",
    },
    {
      question: "¿Qué continúa? 10, 20, 40, 70, 110, __",
      options: ["150", "160", "170", "180"],
      correctAnswer: 1,
      hint: "Diferencias: +10, +20, +30, +40, +50",
    },
    {
      question: "Serie: 3, 9, 27, 81, 243, __",
      options: ["486", "648", "729", "810"],
      correctAnswer: 2,
      hint: "Multiplica por 3 cada vez (potencias de 3)",
    },
    {
      question: "¿Siguiente número? 5, 8, 13, 21, 34, __",
      options: ["47", "52", "55", "60"],
      correctAnswer: 2,
      hint: "Fibonacci modificado: +3, +5, +8, +13, +21",
    },
    {
      question: "Serie: 144, 121, 100, 81, 64, __",
      options: ["49", "48", "45", "50"],
      correctAnswer: 0,
      hint: "Cuadrados descendentes: 12², 11², 10², 9², 8², 7²",
    },
    {
      question: "¿Qué sigue? 0, 1, 1, 2, 3, 5, 8, 13, __",
      options: ["18", "19", "20", "21"],
      correctAnswer: 3,
      hint: "Serie de Fibonacci pura",
    },
    {
      question: "Serie: 4, 8, 16, 32, 64, __",
      options: ["96", "128", "120", "132"],
      correctAnswer: 1,
      hint: "Potencias de 2: 2², 2³, 2⁴, 2⁵, 2⁶, 2⁷",
    },
    {
      question: "¿Siguiente? 11, 22, 33, 44, 55, __",
      options: ["60", "65", "66", "70"],
      correctAnswer: 2,
      hint: "Múltiplos de 11",
    },

    // Álgebra y ecuaciones (21-60)
    {
      question:
        "Si 5 máquinas producen 5 productos en 5 minutos, ¿cuánto tardarán 100 máquinas en producir 100 productos?",
      options: ["100 minutos", "20 minutos", "5 minutos", "10 minutos"],
      correctAnswer: 2,
      hint: "Cada máquina tarda 5 minutos en hacer 1 producto",
    },
    {
      question: "¿Qué número falta en la ecuación? 3 × ? + 5 = 23",
      options: ["6", "8", "5", "7"],
      correctAnswer: 0,
      hint: "Primero resta 5 de 23, luego divide entre 3",
    },
    {
      question: "Si x + 7 = 15, ¿cuánto vale x?",
      options: ["8", "7", "9", "22"],
      correctAnswer: 0,
      hint: "Resta 7 de ambos lados",
    },
    {
      question: "Resuelve: 2x - 4 = 10",
      options: ["6", "7", "8", "5"],
      correctAnswer: 1,
      hint: "Suma 4, luego divide entre 2",
    },
    {
      question: "Si 3y = 27, ¿cuánto vale y?",
      options: ["7", "8", "9", "10"],
      correctAnswer: 2,
      hint: "Divide 27 entre 3",
    },
    {
      question: "¿Qué valor tiene n en: n/4 = 6?",
      options: ["20", "22", "24", "26"],
      correctAnswer: 2,
      hint: "Multiplica 6 por 4",
    },
    {
      question: "Si a + b = 12 y a = 5, ¿cuánto vale b?",
      options: ["5", "6", "7", "8"],
      correctAnswer: 2,
      hint: "Resta 5 de 12",
    },
    {
      question: "Resuelve: 4x + 8 = 32",
      options: ["4", "5", "6", "7"],
      correctAnswer: 2,
      hint: "Resta 8, luego divide entre 4",
    },
    {
      question: "Si 2m - 3 = 11, ¿cuánto vale m?",
      options: ["6", "7", "8", "9"],
      correctAnswer: 1,
      hint: "Suma 3, luego divide entre 2",
    },
    {
      question: "¿Qué valor tiene x en: 5x + 2 = 37?",
      options: ["5", "6", "7", "8"],
      correctAnswer: 2,
      hint: "Resta 2, luego divide entre 5",
    },
    {
      question: "Si x/3 + 4 = 9, ¿cuánto vale x?",
      options: ["12", "15", "18", "21"],
      correctAnswer: 1,
      hint: "Resta 4, luego multiplica por 3",
    },
    {
      question: "Resuelve: 7 + 2x = 21",
      options: ["5", "6", "7", "8"],
      correctAnswer: 2,
      hint: "Resta 7, luego divide entre 2",
    },
    {
      question: "Si 4a = 36, ¿cuánto vale a?",
      options: ["7", "8", "9", "10"],
      correctAnswer: 2,
      hint: "Divide 36 entre 4",
    },
    {
      question: "¿Qué número falta? 6 × ? - 8 = 34",
      options: ["6", "7", "8", "9"],
      correctAnswer: 1,
      hint: "Suma 8, luego divide entre 6",
    },
    {
      question: "Si x + x + 5 = 17, ¿cuánto vale x?",
      options: ["4", "5", "6", "7"],
      correctAnswer: 2,
      hint: "2x + 5 = 17, entonces 2x = 12",
    },
    {
      question: "Resuelve: 3(x + 2) = 18",
      options: ["3", "4", "5", "6"],
      correctAnswer: 1,
      hint: "Divide entre 3 primero: x + 2 = 6",
    },
    {
      question: "Si 5x - 10 = 25, ¿cuánto vale x?",
      options: ["5", "6", "7", "8"],
      correctAnswer: 2,
      hint: "Suma 10, luego divide entre 5",
    },
    {
      question: "¿Qué valor tiene y en: 2y + 7 = 19?",
      options: ["4", "5", "6", "7"],
      correctAnswer: 2,
      hint: "Resta 7, luego divide entre 2",
    },
    {
      question: "Si x/5 = 8, ¿cuánto vale x?",
      options: ["30", "35", "40", "45"],
      correctAnswer: 2,
      hint: "Multiplica 8 por 5",
    },
    {
      question: "Resuelve: 9 - 2x = 1",
      options: ["3", "4", "5", "6"],
      correctAnswer: 1,
      hint: "Resta 9 de ambos lados, luego divide entre -2",
    },
    {
      question: "Si 3x + 4x = 35, ¿cuánto vale x?",
      options: ["3", "4", "5", "6"],
      correctAnswer: 2,
      hint: "7x = 35",
    },
    {
      question: "¿Qué número falta? 8 × ? + 12 = 60",
      options: ["4", "5", "6", "7"],
      correctAnswer: 2,
      hint: "Resta 12, luego divide entre 8",
    },
    {
      question: "Si 10 - 3x = 1, ¿cuánto vale x?",
      options: ["2", "3", "4", "5"],
      correctAnswer: 1,
      hint: "10 - 1 = 3x, entonces 9 = 3x",
    },
    {
      question: "Resuelve: x² = 49",
      options: ["5", "6", "7", "8"],
      correctAnswer: 2,
      hint: "Raíz cuadrada de 49",
    },
    {
      question: "Si 2(x - 3) = 14, ¿cuánto vale x?",
      options: ["8", "9", "10", "11"],
      correctAnswer: 2,
      hint: "Divide entre 2: x - 3 = 7",
    },
    {
      question: "¿Qué valor tiene a en: 4a + 5 = 29?",
      options: ["4", "5", "6", "7"],
      correctAnswer: 2,
      hint: "Resta 5, luego divide entre 4",
    },
    {
      question: "Si 6x - 18 = 30, ¿cuánto vale x?",
      options: ["6", "7", "8", "9"],
      correctAnswer: 2,
      hint: "Suma 18, luego divide entre 6",
    },
    {
      question: "Resuelve: x/2 + 5 = 12",
      options: ["12", "14", "16", "18"],
      correctAnswer: 1,
      hint: "Resta 5, luego multiplica por 2",
    },
    {
      question: "Si 7x + 3 = 52, ¿cuánto vale x?",
      options: ["5", "6", "7", "8"],
      correctAnswer: 2,
      hint: "Resta 3, luego divide entre 7",
    },
    {
      question: "¿Qué número falta? 5 × ? - 15 = 20",
      options: ["5", "6", "7", "8"],
      correctAnswer: 2,
      hint: "Suma 15, luego divide entre 5",
    },
    {
      question: "Si 3x - 2x + 8 = 15, ¿cuánto vale x?",
      options: ["5", "6", "7", "8"],
      correctAnswer: 2,
      hint: "x + 8 = 15",
    },
    {
      question: "Resuelve: 4(2x - 1) = 28",
      options: ["3", "4", "5", "6"],
      correctAnswer: 1,
      hint: "Divide entre 4: 2x - 1 = 7",
    },
    {
      question: "Si x² = 64, ¿cuánto vale x?",
      options: ["6", "7", "8", "9"],
      correctAnswer: 2,
      hint: "Raíz cuadrada de 64",
    },
    {
      question: "¿Qué valor tiene m en: 9m - 27 = 36?",
      options: ["5", "6", "7", "8"],
      correctAnswer: 2,
      hint: "Suma 27, luego divide entre 9",
    },
    {
      question: "Si 2x + 3x - 5 = 20, ¿cuánto vale x?",
      options: ["3", "4", "5", "6"],
      correctAnswer: 2,
      hint: "5x - 5 = 20, entonces 5x = 25",
    },
    {
      question: "Resuelve: 8x/4 = 12",
      options: ["4", "5", "6", "7"],
      correctAnswer: 2,
      hint: "Simplifica: 2x = 12",
    },
    {
      question: "Si 15 - 2x = 5, ¿cuánto vale x?",
      options: ["3", "4", "5", "6"],
      correctAnswer: 2,
      hint: "15 - 5 = 2x, entonces 10 = 2x",
    },
    {
      question: "¿Qué número falta? 3 × ? + 9 = 30",
      options: ["5", "6", "7", "8"],
      correctAnswer: 2,
      hint: "Resta 9, luego divide entre 3",
    },
    {
      question: "Si x/6 + 2 = 7, ¿cuánto vale x?",
      options: ["24", "28", "30", "36"],
      correctAnswer: 2,
      hint: "Resta 2, luego multiplica por 6",
    },
    {
      question: "Resuelve: 5(x - 4) = 15",
      options: ["5", "6", "7", "8"],
      correctAnswer: 2,
      hint: "Divide entre 5: x - 4 = 3",
    },

    // Proporciones y porcentajes (61-100)
    {
      question: "¿Qué porcentaje es 25 de 200?",
      options: ["10.5%", "12.5%", "15%", "20%"],
      correctAnswer: 1,
      hint: "(25/200) × 100",
    },
    {
      question: "Si un artículo cuesta $80 con 20% de descuento, ¿cuál era el precio original?",
      options: ["$96", "$100", "$105", "$110"],
      correctAnswer: 1,
      hint: "80 es el 80% del precio original",
    },
    {
      question: "¿Cuánto es el 15% de 240?",
      options: ["30", "34", "36", "40"],
      correctAnswer: 2,
      hint: "240 × 0.15",
    },
    {
      question: "Si 6 trabajadores completan una tarea en 8 horas, ¿cuánto tardarán 4 trabajadores?",
      options: ["10 horas", "12 horas", "14 horas", "16 horas"],
      correctAnswer: 1,
      hint: "Menos trabajadores = más tiempo. 6×8 = 48 horas-trabajador",
    },
    {
      question: "¿Qué porcentaje es 15 de 60?",
      options: ["20%", "25%", "30%", "35%"],
      correctAnswer: 1,
      hint: "(15/60) × 100",
    },
    {
      question: "Un producto cuesta $120 con 25% de descuento. ¿Precio original?",
      options: ["$150", "$160", "$170", "$180"],
      correctAnswer: 1,
      hint: "120 es el 75% del original",
    },
    {
      question: "¿Cuánto es el 20% de 350?",
      options: ["60", "65", "70", "75"],
      correctAnswer: 2,
      hint: "350 × 0.20",
    },
    {
      question: "Si 3 pintores tardan 6 días, ¿cuánto tardarán 2 pintores?",
      options: ["8 días", "9 días", "10 días", "12 días"],
      correctAnswer: 1,
      hint: "3×6 = 18 días-pintor, entonces 18÷2 = 9",
    },
    {
      question: "¿Qué porcentaje es 40 de 160?",
      options: ["20%", "25%", "30%", "35%"],
      correctAnswer: 1,
      hint: "(40/160) × 100",
    },
    {
      question: "Con 10% de descuento pagas $90. ¿Precio original?",
      options: ["$95", "$100", "$105", "$110"],
      correctAnswer: 1,
      hint: "90 es el 90% del original",
    },
    {
      question: "¿Cuánto es el 30% de 400?",
      options: ["100", "110", "120", "130"],
      correctAnswer: 2,
      hint: "400 × 0.30",
    },
    {
      question: "Si 8 obreros terminan en 5 días, ¿cuánto tardan 10 obreros?",
      options: ["3 días", "4 días", "5 días", "6 días"],
      correctAnswer: 1,
      hint: "8×5 = 40 días-obrero, entonces 40÷10 = 4",
    },
    {
      question: "¿Qué porcentaje es 18 de 72?",
      options: ["20%", "25%", "30%", "35%"],
      correctAnswer: 1,
      hint: "(18/72) × 100",
    },
    {
      question: "Un libro cuesta $45 con 10% de descuento. ¿Precio original?",
      options: ["$48", "$50", "$52", "$55"],
      correctAnswer: 1,
      hint: "45 es el 90% del original",
    },
    {
      question: "¿Cuánto es el 40% de 250?",
      options: ["90", "95", "100", "105"],
      correctAnswer: 2,
      hint: "250 × 0.40",
    },
    {
      question: "Si 12 máquinas producen 60 unidades al día, ¿cuántas producirán 8 máquinas?",
      options: ["35", "40", "45", "50"],
      correctAnswer: 1,
      hint: "12 máquinas = 60, entonces 1 máquina = 5",
    },
    {
      question: "¿Qué porcentaje es 35 de 140?",
      options: ["20%", "25%", "30%", "35%"],
      correctAnswer: 1,
      hint: "(35/140) × 100",
    },
    {
      question: "Con 15% de descuento pagas $85. ¿Precio original?",
      options: ["$95", "$100", "$105", "$110"],
      correctAnswer: 1,
      hint: "85 es el 85% del original",
    },
    {
      question: "¿Cuánto es el 35% de 200?",
      options: ["60", "65", "70", "75"],
      correctAnswer: 2,
      hint: "200 × 0.35",
    },
    {
      question: "Si 5 computadoras procesan datos en 4 horas, ¿cuánto tardan 8 computadoras?",
      options: ["2 horas", "2.5 horas", "3 horas", "3.5 horas"],
      correctAnswer: 1,
      hint: "5×4 = 20 horas-computadora, entonces 20÷8 = 2.5",
    },
    {
      question: "¿Qué porcentaje es 24 de 96?",
      options: ["20%", "25%", "30%", "35%"],
      correctAnswer: 1,
      hint: "(24/96) × 100",
    },
    {
      question: "Un televisor cuesta $640 con 20% de descuento. ¿Precio original?",
      options: ["$750", "$800", "$850", "$900"],
      correctAnswer: 1,
      hint: "640 es el 80% del original",
    },
    {
      question: "¿Cuánto es el 45% de 180?",
      options: ["75", "78", "81", "84"],
      correctAnswer: 2,
      hint: "180 × 0.45",
    },
    {
      question: "Si 7 empleados hacen un trabajo en 9 días, ¿cuánto tardan 3 empleados?",
      options: ["18 días", "21 días", "24 días", "27 días"],
      correctAnswer: 1,
      hint: "7×9 = 63 días-empleado, entonces 63÷3 = 21",
    },
    {
      question: "¿Qué porcentaje es 32 de 128?",
      options: ["20%", "25%", "30%", "35%"],
      correctAnswer: 1,
      hint: "(32/128) × 100",
    },
    {
      question: "Con 30% de descuento pagas $210. ¿Precio original?",
      options: ["$280", "$300", "$320", "$350"],
      correctAnswer: 1,
      hint: "210 es el 70% del original",
    },
    {
      question: "¿Cuánto es el 18% de 450?",
      options: ["75", "78", "81", "84"],
      correctAnswer: 2,
      hint: "450 × 0.18",
    },
    {
      question: "Si 9 camiones transportan carga en 4 viajes, ¿cuántos viajes necesitan 6 camiones?",
      options: ["5", "6", "7", "8"],
      correctAnswer: 1,
      hint: "9×4 = 36 viajes-camión, entonces 36÷6 = 6",
    },
    {
      question: "¿Qué porcentaje es 45 de 180?",
      options: ["20%", "25%", "30%", "35%"],
      correctAnswer: 1,
      hint: "(45/180) × 100",
    },
    {
      question: "Un zapato cuesta $68 con 15% de descuento. ¿Precio original?",
      options: ["$75", "$80", "$85", "$90"],
      correctAnswer: 1,
      hint: "68 es el 85% del original",
    },
    {
      question: "¿Cuánto es el 22% de 550?",
      options: ["115", "119", "121", "125"],
      correctAnswer: 2,
      hint: "550 × 0.22",
    },
    {
      question: "Si 15 máquinas ensamblan productos en 6 horas, ¿cuánto tardan 10 máquinas?",
      options: ["8 horas", "9 horas", "10 horas", "12 horas"],
      correctAnswer: 1,
      hint: "15×6 = 90 horas-máquina, entonces 90÷10 = 9",
    },
    {
      question: "¿Qué porcentaje es 28 de 112?",
      options: ["20%", "25%", "30%", "35%"],
      correctAnswer: 1,
      hint: "(28/112) × 100",
    },
    {
      question: "Con 25% de descuento pagas $375. ¿Precio original?",
      options: ["$450", "$475", "$500", "$525"],
      correctAnswer: 2,
      hint: "375 es el 75% del original",
    },
    {
      question: "¿Cuánto es el 16% de 625?",
      options: ["95", "100", "105", "110"],
      correctAnswer: 1,
      hint: "625 × 0.16",
    },
    {
      question: "Si 20 trabajadores completan en 8 días, ¿cuánto tardan 16 trabajadores?",
      options: ["8 días", "9 días", "10 días", "11 días"],
      correctAnswer: 2,
      hint: "20×8 = 160 días-trabajador, entonces 160÷16 = 10",
    },
    {
      question: "¿Qué porcentaje es 36 de 144?",
      options: ["20%", "25%", "30%", "35%"],
      correctAnswer: 1,
      hint: "(36/144) × 100",
    },
    {
      question: "Un reloj cuesta $170 con 15% de descuento. ¿Precio original?",
      options: ["$190", "$200", "$210", "$220"],
      correctAnswer: 1,
      hint: "170 es el 85% del original",
    },
    {
      question: "¿Cuánto es el 28% de 350?",
      options: ["94", "96", "98", "100"],
      correctAnswer: 2,
      hint: "350 × 0.28",
    },
    {
      question: "Si 24 personas hacen un proyecto en 5 días, ¿cuánto tardan 30 personas?",
      options: ["3 días", "4 días", "5 días", "6 días"],
      correctAnswer: 1,
      hint: "24×5 = 120 días-persona, entonces 120÷30 = 4",
    },

    // Problemas lógico-matemáticos (101-150)
    {
      question:
        "Un tren sale a las 10:00 AM y viaja a 60 km/h. Otro sale a las 11:00 AM a 80 km/h por la misma ruta. ¿A qué hora se encuentran?",
      options: ["1:00 PM", "2:00 PM", "3:00 PM", "4:00 PM"],
      correctAnswer: 2,
      hint: "El primero tiene 60 km de ventaja, se acerca a 20 km/h",
    },
    {
      question: "Si compro 3 manzanas por $6 y 2 naranjas por $5, ¿cuánto pagaré por 5 manzanas y 4 naranjas?",
      options: ["$18", "$20", "$22", "$24"],
      correctAnswer: 1,
      hint: "Manzana = $2, naranja = $2.50",
    },
    {
      question:
        "Un tanque se llena en 6 horas con una llave y se vacía en 9 horas con otra. ¿En cuánto se llena con ambas abiertas?",
      options: ["15 horas", "18 horas", "20 horas", "12 horas"],
      correctAnswer: 1,
      hint: "Tasa neta: 1/6 - 1/9 = 1/18 por hora",
    },
    {
      question:
        "Tengo el doble de edad que tenías cuando yo tenía la edad que tú tienes. Si la suma de nuestras edades es 63, ¿qué edad tienes?",
      options: ["21", "25", "27", "30"],
      correctAnswer: 2,
      hint: "Prueba con las opciones: si tienes 27, yo tengo 36",
    },
    {
      question: "En un grupo de 40 personas, el 60% son mujeres. ¿Cuántos hombres hay?",
      options: ["12", "14", "16", "18"],
      correctAnswer: 2,
      hint: "40% de 40 = 16 hombres",
    },
    {
      question: "Si un reloj da 6 campanadas en 5 segundos, ¿cuánto tardará en dar 12 campanadas?",
      options: ["10 seg", "11 seg", "12 seg", "15 seg"],
      correctAnswer: 1,
      hint: "6 campanadas tienen 5 intervalos de 1 seg cada uno",
    },
    {
      question:
        "Un caracol sube 3 metros de día y baja 2 de noche. Si el poste mide 10 metros, ¿en cuántos días llega arriba?",
      options: ["7 días", "8 días", "9 días", "10 días"],
      correctAnswer: 1,
      hint: "El último día no baja, alcanza la cima durante el día 8",
    },
    {
      question: "Tengo el triple de dinero que tú. Si te doy $20, tendremos lo mismo. ¿Cuánto tengo?",
      options: ["$40", "$50", "$60", "$80"],
      correctAnswer: 2,
      hint: "Si x es lo que tienes, yo tengo 3x. Después: 3x-20 = x+20",
    },
    {
      question: "Un padre tiene 40 años y su hijo 10. ¿En cuántos años la edad del padre será el doble de la del hijo?",
      options: ["15 años", "20 años", "25 años", "30 años"],
      correctAnswer: 1,
      hint: "40+x = 2(10+x), entonces 40+x = 20+2x",
    },
    {
      question:
        "Si 5 gatos cazan 5 ratones en 5 minutos, ¿cuántos gatos se necesitan para cazar 100 ratones en 100 minutos?",
      options: ["5", "10", "20", "100"],
      correctAnswer: 0,
      hint: "Cada gato caza 1 ratón en 5 minutos, entonces 20 en 100 minutos",
    },
    {
      question:
        "Dos velas de igual tamaño: una dura 4 horas y otra 5 horas. Encendidas juntas, ¿cuándo una mide el doble que la otra?",
      options: ["2h 30m", "3h", "3h 20m", "4h"],
      correctAnswer: 2,
      hint: "Velocidades: 1/4 y 1/5. Plantea ecuación de proporciones",
    },
    {
      question: "Un granjero tiene gallinas y conejos: 35 cabezas y 94 patas. ¿Cuántos conejos tiene?",
      options: ["10", "12", "14", "16"],
      correctAnswer: 1,
      hint: "Gallinas tienen 2 patas, conejos 4. Sistema de ecuaciones",
    },
    {
      question: "Si al triple de mi edad le restas 12, obtienes mi edad aumentada en 16. ¿Cuántos años tengo?",
      options: ["12", "14", "16", "18"],
      correctAnswer: 1,
      hint: "3x - 12 = x + 16",
    },
    {
      question: "En una clase, 3/5 son niñas. Si hay 12 niños, ¿cuántos estudiantes hay en total?",
      options: ["25", "28", "30", "32"],
      correctAnswer: 2,
      hint: "Si 3/5 son niñas, 2/5 son niños = 12",
    },
    {
      question: "Un grifo llena una piscina en 12 horas y otro en 8 horas. ¿Cuánto tardan juntos?",
      options: ["4h 20m", "4h 30m", "4h 48m", "5h"],
      correctAnswer: 2,
      hint: "Tasas: 1/12 + 1/8 = 5/24 por hora",
    },
    {
      question: "Si hoy es miércoles, ¿qué día fue hace 100 días?",
      options: ["Domingo", "Lunes", "Martes", "Miércoles"],
      correctAnswer: 0,
      hint: "100 ÷ 7 = 14 semanas + 2 días atrás",
    },
    {
      question: "Un número aumentado en su mitad es 36. ¿Qué número es?",
      options: ["20", "22", "24", "26"],
      correctAnswer: 2,
      hint: "x + x/2 = 36, entonces 3x/2 = 36",
    },
    {
      question:
        "Si 8 obreros construyen una pared en 15 días trabajando 6 horas diarias, ¿cuántos días tardarán 10 obreros trabajando 8 horas diarias?",
      options: ["7 días", "8 días", "9 días", "10 días"],
      correctAnswer: 2,
      hint: "Total horas-obrero: 8×15×6 = 720. Nuevos: 720÷(10×8)",
    },
    {
      question: "La suma de tres números consecutivos es 60. ¿Cuál es el mayor?",
      options: ["19", "20", "21", "22"],
      correctAnswer: 2,
      hint: "x + (x+1) + (x+2) = 60, entonces 3x + 3 = 60",
    },
    {
      question: "Un comerciante compra artículos a $50 y quiere ganar el 40%. ¿A qué precio debe vender?",
      options: ["$65", "$70", "$75", "$80"],
      correctAnswer: 1,
      hint: "50 + (50 × 0.40)",
    },
    {
      question: "Si 3/4 de un tanque contienen 60 litros, ¿cuál es la capacidad total?",
      options: ["75 litros", "80 litros", "85 litros", "90 litros"],
      correctAnswer: 1,
      hint: "(3/4)x = 60, entonces x = 60 × (4/3)",
    },
    {
      question: "Dos números suman 50 y su diferencia es 10. ¿Cuál es el mayor?",
      options: ["25", "28", "30", "32"],
      correctAnswer: 2,
      hint: "x + y = 50, x - y = 10. Suma las ecuaciones: 2x = 60",
    },
    {
      question: "Un tren de 200m cruza un puente de 800m en 50 segundos. ¿Cuál es su velocidad en m/s?",
      options: ["18", "20", "22", "24"],
      correctAnswer: 1,
      hint: "Distancia total: 200 + 800 = 1000m en 50s",
    },
    {
      question: "Si al cuadrado de un número le sumas 9, obtienes 58. ¿Qué número es?",
      options: ["5", "6", "7", "8"],
      correctAnswer: 2,
      hint: "x² + 9 = 58, entonces x² = 49",
    },
    {
      question: "En una bolsa hay $120 en monedas de $5 y $10. Si hay 15 monedas en total, ¿cuántas son de $10?",
      options: ["6", "7", "8", "9"],
      correctAnswer: 2,
      hint: "5x + 10y = 120 y x + y = 15",
    },
    {
      question: "Un rectángulo tiene perímetro 48 cm. Si el largo es el doble del ancho, ¿cuánto mide el largo?",
      options: ["12 cm", "14 cm", "16 cm", "18 cm"],
      correctAnswer: 2,
      hint: "2(x + 2x) = 48, entonces 6x = 48",
    },
    {
      question: "Si invierto $1000 al 5% anual simple, ¿cuánto gano en 3 años?",
      options: ["$120", "$130", "$140", "$150"],
      correctAnswer: 3,
      hint: "Interés = Capital × Tasa × Tiempo",
    },
    {
      question: "La edad de María es 3/4 de la edad de Juan. Si Juan tiene 24 años, ¿cuántos años tiene María?",
      options: ["16", "18", "20", "22"],
      correctAnswer: 1,
      hint: "(3/4) × 24",
    },
    {
      question: "Un auto consume 8 litros cada 100 km. ¿Cuántos litros necesita para 350 km?",
      options: ["26", "27", "28", "29"],
      correctAnswer: 2,
      hint: "(350 ÷ 100) × 8",
    },
    {
      question: "Si 12 es el 30% de un número, ¿cuál es ese número?",
      options: ["35", "38", "40", "42"],
      correctAnswer: 2,
      hint: "12 = 0.30x, entonces x = 12 ÷ 0.30",
    },
    {
      question: "Dos números están en razón 3:5 y suman 64. ¿Cuál es el menor?",
      options: ["20", "22", "24", "26"],
      correctAnswer: 2,
      hint: "3x + 5x = 64, entonces 8x = 64",
    },
    {
      question: "Un televisor costaba $800 y bajó 15%. Luego subió 15%. ¿Precio final?",
      options: ["$778", "$782", "$786", "$800"],
      correctAnswer: 0,
      hint: "800 × 0.85 × 1.15 = 782 (pero watch: no regresa al original)",
    },
    {
      question: "Si x/3 = y/4 y x + y = 35, ¿cuánto vale x?",
      options: ["12", "15", "18", "20"],
      correctAnswer: 1,
      hint: "x = (3/4)y, sustituye: (3/4)y + y = 35",
    },
    {
      question: "Un ciclista recorre 3/5 de su ruta en 2 horas. ¿Cuánto tardará en total a la misma velocidad?",
      options: ["3h", "3h 20m", "3h 30m", "4h"],
      correctAnswer: 1,
      hint: "(3/5) del tiempo = 2h, entonces tiempo total = 2 ÷ (3/5)",
    },
    {
      question: "Si a = 2b y b = 3c, ¿cuál es la razón entre a y c?",
      options: ["5:1", "6:1", "7:1", "8:1"],
      correctAnswer: 1,
      hint: "a = 2b = 2(3c) = 6c",
    },
    {
      question: "La diferencia entre dos números es 18 y su cociente es 4. ¿Cuál es el menor?",
      options: ["4", "5", "6", "7"],
      correctAnswer: 2,
      hint: "x - y = 18 y x/y = 4, entonces x = 4y",
    },
    {
      question: "Un triángulo tiene ángulos en razón 2:3:4. ¿Cuánto mide el ángulo mayor?",
      options: ["60°", "70°", "80°", "90°"],
      correctAnswer: 2,
      hint: "2x + 3x + 4x = 180°, entonces 9x = 180°",
    },
    {
      question: "Si el precio aumenta 25% y luego baja 25%, ¿qué porcentaje del precio original queda?",
      options: ["93.75%", "95%", "97.5%", "100%"],
      correctAnswer: 0,
      hint: "100 × 1.25 × 0.75 = 93.75",
    },
    {
      question: "Un número multiplicado por 7 y disminuido en 12 da 44. ¿Qué número es?",
      options: ["6", "7", "8", "9"],
      correctAnswer: 2,
      hint: "7x - 12 = 44",
    },
    {
      question: "En un mezcla de 80 litros con 25% de alcohol, ¿cuántos litros de agua hay?",
      options: ["50", "55", "60", "65"],
      correctAnswer: 2,
      hint: "75% de 80 litros",
    },
    {
      question: "Si 5 libros cuestan lo mismo que 3 cuadernos y un cuaderno cuesta $15, ¿cuánto cuesta un libro?",
      options: ["$7", "$8", "$9", "$10"],
      correctAnswer: 2,
      hint: "5 libros = 3 × $15 = $45, entonces libro = $45 ÷ 5",
    },
    {
      question: "Un recipiente tiene 2/3 de agua. Si se agregan 10 litros, queda lleno. ¿Cuál es su capacidad?",
      options: ["25 litros", "28 litros", "30 litros", "32 litros"],
      correctAnswer: 2,
      hint: "(1 - 2/3)x = 10, entonces (1/3)x = 10",
    },
    {
      question: "La suma de dos números es 90. Si uno es 5/4 del otro, ¿cuál es el mayor?",
      options: ["45", "48", "50", "52"],
      correctAnswer: 2,
      hint: "x + (5/4)x = 90, entonces (9/4)x = 90",
    },
    {
      question:
        "Un trabajo lo hacen 6 personas en 12 días. Si después de 4 días se retiran 2, ¿en cuántos días más terminarán?",
      options: ["10", "11", "12", "13"],
      correctAnswer: 2,
      hint: "Trabajo restante: 2/3. Personas restantes: 4. Usa proporciones",
    },
    {
      question: "Si x² - 5x + 6 = 0, ¿cuáles son los valores de x?",
      options: ["1 y 6", "2 y 3", "2 y 4", "3 y 4"],
      correctAnswer: 1,
      hint: "Factoriza: (x-2)(x-3) = 0",
    },
    {
      question:
        "Un reloj se adelanta 3 minutos cada hora. Si lo ajustas a las 6:00 AM, ¿qué hora marca cuando son las 2:00 PM?",
      options: ["2:18 PM", "2:20 PM", "2:24 PM", "2:30 PM"],
      correctAnswer: 2,
      hint: "8 horas × 3 minutos = 24 minutos adelantado",
    },
    {
      question: "En un grupo, 40% estudian inglés, 30% francés y 20% ambos. ¿Qué porcentaje no estudia ninguno?",
      options: ["10%", "20%", "30%", "50%"],
      correctAnswer: 2,
      hint: "Inglés + Francés - Ambos = 40 + 30 - 20 = 50%",
    },
    {
      question:
        "Un número es 3 veces otro. Si el mayor disminuye en 15 y el menor aumenta en 5, son iguales. ¿Cuál es el número mayor?",
      options: ["24", "27", "30", "33"],
      correctAnswer: 2,
      hint: "3x - 15 = x + 5",
    },
    {
      question: "Si 2/5 de una obra se hace en 8 días, ¿en cuántos días se hará toda la obra?",
      options: ["18", "20", "22", "24"],
      correctAnswer: 1,
      hint: "(2/5) de días = 8, entonces días totales = 8 ÷ (2/5)",
    },

    // Geometría y medidas (151-200)
    {
      question: "¿Cuál es el área de un rectángulo de 8 cm × 5 cm?",
      options: ["35 cm²", "40 cm²", "45 cm²", "50 cm²"],
      correctAnswer: 1,
      hint: "Área = largo × ancho",
    },
    {
      question: "¿Cuántos grados suman los ángulos internos de un triángulo?",
      options: ["90°", "180°", "270°", "360°"],
      correctAnswer: 1,
      hint: "Propiedad fundamental de los triángulos",
    },
    {
      question: "Si el perímetro de un cuadrado es 36 cm, ¿cuánto mide cada lado?",
      options: ["6 cm", "8 cm", "9 cm", "12 cm"],
      correctAnswer: 2,
      hint: "Perímetro = 4 × lado",
    },
    {
      question: "¿Cuál es el área de un círculo con radio 3 cm? (π ≈ 3.14)",
      options: ["18.84 cm²", "28.26 cm²", "31.4 cm²", "37.68 cm²"],
      correctAnswer: 1,
      hint: "Área = π × r²",
    },
    {
      question: "¿Cuántos grados suman los ángulos internos de un cuadrilátero?",
      options: ["180°", "270°", "360°", "450°"],
      correctAnswer: 2,
      hint: "Fórmula: (n-2) × 180° donde n = número de lados",
    },
    {
      question: "El perímetro de un rectángulo es 30 cm. Si el largo es 10 cm, ¿cuánto mide el ancho?",
      options: ["3 cm", "5 cm", "7 cm", "10 cm"],
      correctAnswer: 1,
      hint: "Perímetro = 2(largo + ancho)",
    },
    {
      question: "¿Cuál es el área de un triángulo con base 8 cm y altura 5 cm?",
      options: ["15 cm²", "20 cm²", "25 cm²", "40 cm²"],
      correctAnswer: 1,
      hint: "Área = (base × altura) ÷ 2",
    },
    {
      question: "¿Cuánto mide la diagonal de un cuadrado de lado 10 cm?",
      options: ["12.5 cm", "14.14 cm", "15 cm", "17.32 cm"],
      correctAnswer: 1,
      hint: "Diagonal = lado × √2",
    },
    {
      question: "¿Cuál es el volumen de un cubo de lado 4 cm?",
      options: ["48 cm³", "54 cm³", "60 cm³", "64 cm³"],
      correctAnswer: 3,
      hint: "Volumen = lado³",
    },
    {
      question: "Un círculo tiene diámetro 14 cm. ¿Cuál es su radio?",
      options: ["5 cm", "6 cm", "7 cm", "8 cm"],
      correctAnswer: 2,
      hint: "Radio = diámetro ÷ 2",
    },
    {
      question: "¿Cuántos lados tiene un hexágono?",
      options: ["5", "6", "7", "8"],
      correctAnswer: 1,
      hint: "Hexa = 6",
    },
    {
      question: "El área de un cuadrado es 49 cm². ¿Cuánto mide su lado?",
      options: ["5 cm", "6 cm", "7 cm", "8 cm"],
      correctAnswer: 2,
      hint: "Lado = √área",
    },
    {
      question: "¿Cuál es el perímetro de un triángulo equilátero de lado 6 cm?",
      options: ["12 cm", "15 cm", "18 cm", "21 cm"],
      correctAnswer: 2,
      hint: "Perímetro = 3 × lado (todos los lados iguales)",
    },
    {
      question: "¿Cuál es el área de un paralelogramo con base 9 cm y altura 4 cm?",
      options: ["30 cm²", "34 cm²", "36 cm²", "40 cm²"],
      correctAnswer: 2,
      hint: "Área = base × altura",
    },
    {
      question: "¿Cuántos grados mide un ángulo recto?",
      options: ["45°", "60°", "90°", "180°"],
      correctAnswer: 2,
      hint: "Un cuarto de círculo completo",
    },
    {
      question: "Si un rectángulo tiene área 60 cm² y ancho 5 cm, ¿cuánto mide el largo?",
      options: ["10 cm", "12 cm", "15 cm", "18 cm"],
      correctAnswer: 1,
      hint: "Largo = área ÷ ancho",
    },
    {
      question: "¿Cuál es la circunferencia de un círculo con radio 5 cm? (π ≈ 3.14)",
      options: ["25.7 cm", "28.4 cm", "31.4 cm", "35.1 cm"],
      correctAnswer: 2,
      hint: "Circunferencia = 2 × π × r",
    },
    {
      question: "Un triángulo tiene un ángulo de 90° y otro de 45°. ¿Cuánto mide el tercero?",
      options: ["30°", "35°", "40°", "45°"],
      correctAnswer: 3,
      hint: "Los tres ángulos suman 180°",
    },
    {
      question: "¿Cuál es el volumen de una caja de 5 cm × 4 cm × 3 cm?",
      options: ["48 cm³", "52 cm³", "60 cm³", "72 cm³"],
      correctAnswer: 2,
      hint: "Volumen = largo × ancho × alto",
    },
    {
      question: "¿Cuántos vértices tiene un octágono?",
      options: ["6", "7", "8", "9"],
      correctAnswer: 2,
      hint: "Octa = 8",
    },
    {
      question: "El perímetro de un pentágono regular es 35 cm. ¿Cuánto mide cada lado?",
      options: ["5 cm", "6 cm", "7 cm", "8 cm"],
      correctAnswer: 2,
      hint: "Todos los lados son iguales en un polígono regular",
    },
    {
      question: "¿Cuál es el área de un trapecio con bases 8 cm y 6 cm y altura 5 cm?",
      options: ["30 cm²", "32 cm²", "35 cm²", "40 cm²"],
      correctAnswer: 2,
      hint: "Área = [(base mayor + base menor) × altura] ÷ 2",
    },
    {
      question: "¿Cuántos ángulos rectos tiene un rectángulo?",
      options: ["2", "3", "4", "5"],
      correctAnswer: 2,
      hint: "Todos los ángulos de un rectángulo son rectos",
    },
    {
      question: "Si un triángulo tiene lados 3, 4 y 5 cm, ¿qué tipo de triángulo es?",
      options: ["Equilátero", "Isósceles", "Escaleno", "Rectángulo"],
      correctAnswer: 3,
      hint: "3² + 4² = 5² (Teorema de Pitágoras)",
    },
    {
      question: "¿Cuál es el área de un rombo con diagonales de 8 cm y 6 cm?",
      options: ["20 cm²", "22 cm²", "24 cm²", "28 cm²"],
      correctAnswer: 2,
      hint: "Área = (diagonal₁ × diagonal₂) ÷ 2",
    },
    {
      question: "Un ángulo mide 135°. ¿Qué tipo de ángulo es?",
      options: ["Agudo", "Recto", "Obtuso", "Llano"],
      correctAnswer: 2,
      hint: "Obtuso = mayor que 90° y menor que 180°",
    },
    {
      question: "¿Cuántas caras tiene un cubo?",
      options: ["4", "5", "6", "8"],
      correctAnswer: 2,
      hint: "Cuenta todas las superficies planas",
    },
    {
      question: "El radio de una esfera es 3 cm. ¿Cuál es su volumen? (π ≈ 3.14)",
      options: ["103.6 cm³", "113.04 cm³", "123.4 cm³", "133.2 cm³"],
      correctAnswer: 1,
      hint: "Volumen = (4/3) × π × r³",
    },
    {
      question: "¿Cuál es el área de un círculo con diámetro 10 cm? (π ≈ 3.14)",
      options: ["68.5 cm²", "74.8 cm²", "78.5 cm²", "82.3 cm²"],
      correctAnswer: 2,
      hint: "Primero encuentra el radio: 10÷2 = 5. Luego π × r²",
    },
    {
      question:
        "Un triángulo isósceles tiene dos lados de 8 cm. Si el perímetro es 22 cm, ¿cuánto mide el tercer lado?",
      options: ["4 cm", "5 cm", "6 cm", "7 cm"],
      correctAnswer: 2,
      hint: "8 + 8 + x = 22",
    },
    {
      question: "¿Cuántos grados mide un ángulo llano?",
      options: ["90°", "120°", "180°", "270°"],
      correctAnswer: 2,
      hint: "Es una línea recta",
    },
    {
      question: "El área de un rectángulo es 72 cm². Si el largo es el triple del ancho, ¿cuánto mide el ancho?",
      options: ["4 cm", "5 cm", "6 cm", "8 cm"],
      correctAnswer: 2,
      hint: "x × 3x = 72, entonces 3x² = 72",
    },
    {
      question: "¿Cuántas aristas tiene un prisma rectangular?",
      options: ["8", "10", "12", "14"],
      correctAnswer: 2,
      hint: "Cuenta las líneas donde se encuentran las caras",
    },
    {
      question: "Un cilindro tiene radio 2 cm y altura 5 cm. ¿Cuál es su volumen? (π ≈ 3.14)",
      options: ["52.8 cm³", "56.3 cm³", "62.8 cm³", "68.2 cm³"],
      correctAnswer: 2,
      hint: "Volumen = π × r² × h",
    },
    {
      question: "¿Qué fracción del círculo representa un ángulo de 90°?",
      options: ["1/2", "1/3", "1/4", "1/6"],
      correctAnswer: 2,
      hint: "90° es 1/4 de 360°",
    },
    {
      question: "El lado de un cuadrado aumenta al doble. ¿Cómo cambia el área?",
      options: ["Se duplica", "Se triplica", "Se cuadruplica", "Se sextuplica"],
      correctAnswer: 2,
      hint: "Si lado = x, área = x². Si lado = 2x, área = 4x²",
    },
    {
      question: "¿Cuántas diagonales tiene un pentágono?",
      options: ["3", "4", "5", "6"],
      correctAnswer: 2,
      hint: "Fórmula: n(n-3)/2 donde n = 5",
    },
    {
      question: "Un cono tiene radio 3 cm y altura 4 cm. ¿Cuál es su volumen? (π ≈ 3.14)",
      options: ["32.6 cm³", "35.8 cm³", "37.68 cm³", "40.2 cm³"],
      correctAnswer: 2,
      hint: "Volumen = (1/3) × π × r² × h",
    },
    {
      question: "Si el radio de un círculo se duplica, ¿cómo cambia el área?",
      options: ["Se duplica", "Se triplica", "Se cuadruplica", "Se sextuplica"],
      correctAnswer: 2,
      hint: "Área original: πr². Nueva área: π(2r)² = 4πr²",
    },
    {
      question: "¿Cuál es la suma de los ángulos internos de un hexágono?",
      options: ["540°", "600°", "720°", "900°"],
      correctAnswer: 2,
      hint: "(n-2) × 180° donde n = 6",
    },
    {
      question: "Un rectángulo tiene diagonal 13 cm y un lado 5 cm. ¿Cuánto mide el otro lado?",
      options: ["10 cm", "11 cm", "12 cm", "14 cm"],
      correctAnswer: 2,
      hint: "Usa Pitágoras: 5² + x² = 13²",
    },
    {
      question: "¿Cuál es el área lateral de un cilindro con radio 3 cm y altura 7 cm? (π ≈ 3.14)",
      options: ["121.8 cm²", "131.88 cm²", "141.2 cm²", "151.6 cm²"],
      correctAnswer: 1,
      hint: "Área lateral = 2 × π × r × h",
    },
    {
      question: "Dos ángulos son suplementarios. Si uno mide 65°, ¿cuánto mide el otro?",
      options: ["105°", "110°", "115°", "120°"],
      correctAnswer: 2,
      hint: "Suplementarios suman 180°",
    },
    {
      question: "Un triángulo rectángulo tiene catetos de 6 cm y 8 cm. ¿Cuánto mide la hipotenusa?",
      options: ["9 cm", "10 cm", "11 cm", "12 cm"],
      correctAnswer: 1,
      hint: "Pitágoras: c² = 6² + 8²",
    },
    {
      question: "¿Cuántas caras tiene una pirámide cuadrangular?",
      options: ["4", "5", "6", "8"],
      correctAnswer: 1,
      hint: "Base cuadrada + 4 caras triangulares",
    },
    {
      question: "El perímetro de un cuadrado es 52 cm. ¿Cuál es su área?",
      options: ["156 cm²", "169 cm²", "180 cm²", "196 cm²"],
      correctAnswer: 1,
      hint: "Lado = 52÷4 = 13. Área = 13²",
    },
    {
      question: "Dos ángulos son complementarios. Si uno mide 35°, ¿cuánto mide el otro?",
      options: ["45°", "50°", "55°", "60°"],
      correctAnswer: 2,
      hint: "Complementarios suman 90°",
    },
    {
      question: "¿Cuál es el área total de un cubo de lado 5 cm?",
      options: ["120 cm²", "130 cm²", "140 cm²", "150 cm²"],
      correctAnswer: 3,
      hint: "6 caras, cada una 5² = 25 cm²",
    },
    {
      question: "Un paralelogramo tiene base 12 cm y altura 7 cm. ¿Cuál es su área?",
      options: ["72 cm²", "78 cm²", "84 cm²", "90 cm²"],
      correctAnswer: 2,
      hint: "Área = base × altura",
    },

    // Probabilidad y estadística (201-240)
    {
      question: "Al lanzar un dado, ¿cuál es la probabilidad de sacar un número par?",
      options: ["1/6", "1/3", "1/2", "2/3"],
      correctAnswer: 2,
      hint: "Números pares: 2, 4, 6. Total: 6 caras",
    },
    {
      question: "En una bolsa hay 5 bolas rojas y 3 azules. ¿Probabilidad de sacar una roja?",
      options: ["3/8", "5/8", "1/2", "2/3"],
      correctAnswer: 1,
      hint: "5 rojas de 8 totales",
    },
    {
      question: "¿Cuál es la probabilidad de sacar un as de una baraja de 52 cartas?",
      options: ["1/13", "1/26", "1/52", "4/52"],
      correctAnswer: 0,
      hint: "Hay 4 ases en 52 cartas = 4/52 = 1/13",
    },
    {
      question: "Si lanzas dos monedas, ¿cuál es la probabilidad de obtener dos caras?",
      options: ["1/2", "1/3", "1/4", "1/6"],
      correctAnswer: 2,
      hint: "Resultados posibles: CC, CS, SC, SS. Solo 1 de 4",
    },
    {
      question: "En una urna hay 4 bolas verdes, 3 rojas y 5 azules. ¿Probabilidad de sacar verde?",
      options: ["1/3", "1/4", "1/2", "5/12"],
      correctAnswer: 0,
      hint: "4 verdes de 12 totales = 4/12 = 1/3",
    },
    {
      question: "Al lanzar un dado, ¿probabilidad de sacar un número mayor que 4?",
      options: ["1/6", "1/3", "1/2", "2/3"],
      correctAnswer: 1,
      hint: "Números mayores que 4: 5 y 6. Son 2 de 6",
    },
    {
      question: "El promedio de 5, 8, 10 y 13 es:",
      options: ["8", "9", "10", "11"],
      correctAnswer: 1,
      hint: "Suma todos y divide entre 4",
    },
    {
      question: "La mediana de 3, 7, 5, 9, 11 es:",
      options: ["5", "7", "8", "9"],
      correctAnswer: 1,
      hint: "Ordena: 3, 5, 7, 9, 11. El del medio es la mediana",
    },
    {
      question: "Si lanzas un dado dos veces, ¿probabilidad de que la suma sea 7?",
      options: ["1/6", "1/4", "1/3", "5/36"],
      correctAnswer: 0,
      hint: "Combinaciones que suman 7: (1,6), (2,5), (3,4), (4,3), (5,2), (6,1) = 6 de 36",
    },
    {
      question: "La moda de 2, 3, 3, 4, 5, 5, 5, 6 es:",
      options: ["3", "4", "5", "6"],
      correctAnswer: 2,
      hint: "El número que más se repite",
    },
    {
      question: "En una ruleta con números del 1 al 10, ¿probabilidad de salir impar?",
      options: ["1/4", "2/5", "1/2", "3/5"],
      correctAnswer: 2,
      hint: "Impares: 1, 3, 5, 7, 9 = 5 de 10",
    },
    {
      question: "El rango de 12, 8, 15, 3, 20 es:",
      options: ["14", "15", "17", "20"],
      correctAnswer: 2,
      hint: "Rango = valor máximo - valor mínimo",
    },
    {
      question: "Si extraes una carta de una baraja, ¿probabilidad de que sea corazón?",
      options: ["1/13", "1/4", "1/3", "1/2"],
      correctAnswer: 1,
      hint: "13 corazones de 52 cartas = 13/52 = 1/4",
    },
    {
      question: "El promedio de 20, 25, 30 y x es 25. ¿cuánto vale x?",
      options: ["20", "22", "25", "30"],
      correctAnswer: 2,
      hint: "(20 + 25 + 30 + x) / 4 = 25",
    },
    {
      question: "Al lanzar tres monedas, ¿probabilidad de obtener exactamente dos caras?",
      options: ["1/4", "3/8", "1/2", "5/8"],
      correctAnswer: 1,
      hint: "Casos: CCC, CCS, CSC, SCC, CSS, SCS, SSC, SSS. 3 tienen dos caras",
    },
    {
      question: "La mediana de 10, 15, 20, 25 es:",
      options: ["15", "17.5", "18", "20"],
      correctAnswer: 1,
      hint: "Con números pares de datos, promedia los dos del medio",
    },
    {
      question: "En un grupo de 30 estudiantes, 18 son mujeres. ¿Probabilidad de elegir un hombre?",
      options: ["2/5", "3/5", "1/2", "2/3"],
      correctAnswer: 0,
      hint: "Hombres = 30 - 18 = 12. Probabilidad = 12/30 = 2/5",
    },
    {
      question: "¿Cuál es el promedio de los primeros 5 números primos?",
      options: ["5.4", "5.6", "5.8", "6"],
      correctAnswer: 1,
      hint: "2, 3, 5, 7, 11. Suma = 28, promedio = 28/5 = 5.6",
    },
    {
      question: "Si P(A) = 0.3 y P(B) = 0.4, y son independientes, ¿cuál es P(A y B)?",
      options: ["0.07", "0.10", "0.12", "0.15"],
      correctAnswer: 2,
      hint: "P(A y B) = P(A) × P(B) para eventos independientes",
    },
    {
      question: "La desviación estándar mide:",
      options: ["Tendencia central", "Dispersión", "Frecuencia", "Mediana"],
      correctAnswer: 1,
      hint: "Qué tan dispersos están los datos respecto al promedio",
    },
    {
      question: "En un salón, 12 de 20 estudiantes aprobaron. ¿Qué porcentaje aprobó?",
      options: ["50%", "55%", "60%", "65%"],
      correctAnswer: 2,
      hint: "(12/20) × 100",
    },
    {
      question: "Al lanzar un dado, ¿probabilidad de sacar múltiplo de 3?",
      options: ["1/6", "1/3", "1/2", "2/3"],
      correctAnswer: 1,
      hint: "Múltiplos de 3: 3 y 6 = 2 de 6",
    },
    {
      question: "El promedio de 7, 14 y x es 10. ¿Cuánto vale x?",
      options: ["7", "8", "9", "10"],
      correctAnswer: 2,
      hint: "(7 + 14 + x) / 3 = 10",
    },
    {
      question: "Si extraes dos cartas sin reemplazo, ¿probabilidad de dos ases?",
      options: ["1/169", "1/221", "1/256", "1/289"],
      correctAnswer: 1,
      hint: "(4/52) × (3/51) = 12/2652 = 1/221",
    },
    {
      question: "La moda de un conjunto de datos es:",
      options: ["El promedio", "El valor medio", "El más frecuente", "El rango"],
      correctAnswer: 2,
      hint: "El dato que más se repite",
    },
    {
      question: "En una bolsa con 6 bolas numeradas del 1 al 6, ¿probabilidad de sacar primo?",
      options: ["1/3", "1/2", "2/3", "5/6"],
      correctAnswer: 1,
      hint: "Primos: 2, 3, 5 = 3 de 6",
    },
    {
      question: "El percentil 75 indica que:",
      options: ["75% están debajo", "75% están arriba", "Es el promedio", "Es la mediana"],
      correctAnswer: 0,
      hint: "El 75% de los datos son menores o iguales a ese valor",
    },
    {
      question: "Si P(A) = 0.6, ¿cuál es P(no A)?",
      options: ["0.2", "0.3", "0.4", "0.5"],
      correctAnswer: 2,
      hint: "P(no A) = 1 - P(A)",
    },
    {
      question: "El promedio de 5 números es 12. Si se agrega el número 18, ¿cuál es el nuevo promedio?",
      options: ["12", "13", "14", "15"],
      correctAnswer: 1,
      hint: "Suma total original: 60. Nueva suma: 78. Nuevo promedio: 78/6",
    },
    {
      question: "Al lanzar dos dados, ¿probabilidad de obtener suma par?",
      options: ["1/4", "1/3", "1/2", "2/3"],
      correctAnswer: 2,
      hint: "Par+Par=Par, Impar+Impar=Par. Mitad de los casos",
    },
    {
      question: "La varianza es:",
      options: ["Promedio de desviaciones", "Cuadrado de desviación estándar", "Raíz de mediana", "Suma de datos"],
      correctAnswer: 1,
      hint: "Desviación estándar al cuadrado",
    },
    {
      question: "En un examen, las notas fueron 60, 70, 80, 90. ¿Cuál es la mediana?",
      options: ["70", "72", "75", "80"],
      correctAnswer: 2,
      hint: "Promedio de 70 y 80",
    },
    {
      question: "Si lanzas una moneda 3 veces, ¿probabilidad de al menos una cara?",
      options: ["1/2", "5/8", "3/4", "7/8"],
      correctAnswer: 3,
      hint: "P(al menos 1) = 1 - P(ninguna cara) = 1 - 1/8",
    },
    {
      question: "El coeficiente de variación mide:",
      options: ["Dispersión relativa", "Tendencia central", "Asimetría", "Curtosis"],
      correctAnswer: 0,
      hint: "(Desviación estándar / Media) × 100",
    },
    {
      question:
        "En un grupo, el 40% estudia inglés y el 60% matemáticas. Si 20% estudia ambos, ¿qué porcentaje estudia al menos una?",
      options: ["60%", "70%", "80%", "100%"],
      correctAnswer: 2,
      hint: "40 + 60 - 20 = 80",
    },
    {
      question: "El primer cuartil (Q1) es equivalente al percentil:",
      options: ["10", "25", "50", "75"],
      correctAnswer: 1,
      hint: "Q1 = Percentil 25",
    },
    {
      question: "Si dos eventos son mutuamente excluyentes con P(A)=0.3 y P(B)=0.5, ¿cuál es P(A o B)?",
      options: ["0.15", "0.65", "0.8", "0.85"],
      correctAnswer: 2,
      hint: "P(A o B) = P(A) + P(B) si son mutuamente excluyentes",
    },
    {
      question: "El promedio ponderado de 80 (peso 3) y 90 (peso 2) es:",
      options: ["82", "84", "85", "86"],
      correctAnswer: 1,
      hint: "(80×3 + 90×2) / (3+2)",
    },
    {
      question: "Al seleccionar al azar de {1,2,3,4,5,6,7,8,9,10}, ¿probabilidad de número cuadrado perfecto?",
      options: ["1/10", "2/10", "3/10", "4/10"],
      correctAnswer: 2,
      hint: "Cuadrados perfectos: 1, 4, 9 = 3 de 10",
    },
    {
      question: "Si la mediana es 50 y la media es 55, los datos están:",
      options: ["Simétricos", "Sesgados a la izquierda", "Sesgados a la derecha", "Sin varianza"],
      correctAnswer: 2,
      hint: "Media > Mediana indica sesgo a la derecha (cola derecha)",
    },

    // Operaciones mixtas y desafíos (241-300)
    {
      question: "¿Cuánto es (15 + 5) × 2 - 8?",
      options: ["32", "34", "36", "38"],
      correctAnswer: 0,
      hint: "Primero paréntesis, luego multiplicación, finalmente resta",
    },
    {
      question: "Resuelve: 100 ÷ 4 + 6 × 3",
      options: ["40", "43", "45", "48"],
      correctAnswer: 1,
      hint: "División y multiplicación primero: 25 + 18",
    },
    {
      question: "¿Resultado de: 8² - 3² + 5?",
      options: ["50", "58", "60", "68"],
      correctAnswer: 2,
      hint: "64 - 9 + 5",
    },
    {
      question: "Si 2x + 3y = 13 y x = 2, ¿cuánto vale y?",
      options: ["2", "3", "4", "5"],
      correctAnswer: 1,
      hint: "Sustituye x=2: 4 + 3y = 13",
    },
    {
      question: "¿Cuál es el MCM de 6 y 8?",
      options: ["12", "16", "24", "48"],
      correctAnswer: 2,
      hint: "Mínimo común múltiplo",
    },
    {
      question: "¿Cuál es el MCD de 12 y 18?",
      options: ["2", "3", "6", "9"],
      correctAnswer: 2,
      hint: "Máximo común divisor",
    },
    {
      question: "¿Cuántos números primos hay entre 1 y 10?",
      options: ["3", "4", "5", "6"],
      correctAnswer: 1,
      hint: "2, 3, 5, 7",
    },
    {
      question: "Si un número es divisible por 2 y 3, ¿por qué otro número también es divisible?",
      options: ["5", "6", "7", "8"],
      correctAnswer: 1,
      hint: "2 × 3 = 6",
    },
    {
      question: "Un automóvil recorre 240 km en 3 horas. ¿Cuál es su velocidad promedio?",
      options: ["70 km/h", "75 km/h", "80 km/h", "85 km/h"],
      correctAnswer: 2,
      hint: "Velocidad = distancia ÷ tiempo",
    },
    {
      question: "Si 3 libros cuestan $45, ¿cuánto costarán 7 libros?",
      options: ["$95", "$100", "$105", "$110"],
      correctAnswer: 2,
      hint: "Precio por libro = $15",
    },
    {
      question: "¿Cuántos minutos hay en 2.5 horas?",
      options: ["120", "130", "140", "150"],
      correctAnswer: 3,
      hint: "2.5 × 60",
    },
    {
      question: "Si hoy es martes, ¿qué día será en 100 días?",
      options: ["Lunes", "Martes", "Miércoles", "Jueves"],
      correctAnswer: 3,
      hint: "100 ÷ 7 = 14 semanas + 2 días",
    },
    {
      question: "¿Cuánto es 3/4 + 1/2?",
      options: ["1", "5/4", "4/6", "7/8"],
      correctAnswer: 1,
      hint: "Convierte a denominador común: 3/4 + 2/4 = 5/4",
    },
    {
      question: "Simplifica: 12/16",
      options: ["2/3", "3/4", "4/5", "5/6"],
      correctAnswer: 1,
      hint: "Divide numerador y denominador entre 4",
    },
    {
      question: "¿Cuánto es 0.75 + 0.25?",
      options: ["0.9", "1", "1.1", "1.25"],
      correctAnswer: 1,
      hint: "75 centésimos + 25 centésimos",
    },
    {
      question: "¿Qué fracción es equivalente a 0.6?",
      options: ["1/2", "2/3", "3/5", "4/5"],
      correctAnswer: 2,
      hint: "0.6 = 6/10 = 3/5",
    },
    {
      question: "¿Cuánto es 2³ + 3²?",
      options: ["13", "15", "17", "19"],
      correctAnswer: 2,
      hint: "8 + 9 = 17",
    },
    {
      question: "Si n! = 120, ¿cuánto vale n?",
      options: ["4", "5", "6", "7"],
      correctAnswer: 1,
      hint: "5! = 5×4×3×2×1 = 120",
    },
    {
      question: "¿Cuánto es √144?",
      options: ["10", "11", "12", "13"],
      correctAnswer: 2,
      hint: "12² = 144",
    },
    {
      question: "¿Cuál es el valor de 4⁰?",
      options: ["0", "1", "4", "16"],
      correctAnswer: 1,
      hint: "Cualquier número elevado a 0 es 1",
    },
    {
      question: "¿Cuánto es 5! / 3!?",
      options: ["10", "15", "20", "25"],
      correctAnswer: 2,
      hint: "120 / 6 = 20 (o simplifica: 5×4 = 20)",
    },
    {
      question: "Si log₂(x) = 4, ¿cuánto vale x?",
      options: ["8", "12", "16", "20"],
      correctAnswer: 2,
      hint: "2⁴ = 16",
    },
    {
      question: "¿Cuánto es |-8|?",
      options: ["-8", "0", "8", "16"],
      correctAnswer: 2,
      hint: "Valor absoluto siempre es positivo",
    },
    {
      question: "¿Cuál es el siguiente número primo después de 13?",
      options: ["14", "15", "17", "19"],
      correctAnswer: 2,
      hint: "14, 15, 16 son compuestos",
    },
    {
      question: "¿Cuánto es 0.1 × 0.1?",
      options: ["0.01", "0.1", "0.11", "1"],
      correctAnswer: 0,
      hint: "Multiplica como números normales, luego cuenta decimales",
    },
    {
      question: "Si x³ = 64, ¿cuánto vale x?",
      options: ["2", "3", "4", "8"],
      correctAnswer: 2,
      hint: "4³ = 64",
    },
    {
      question: "¿Cuánto es 10% de 10% de 1000?",
      options: ["1", "10", "100", "110"],
      correctAnswer: 1,
      hint: "0.1 × 0.1 × 1000 = 10",
    },
    {
      question: "¿Cuál es la razón entre 20 y 80?",
      options: ["1:2", "1:3", "1:4", "2:5"],
      correctAnswer: 2,
      hint: "20/80 = 1/4",
    },
    {
      question: "Si 2ˣ = 32, ¿cuánto vale x?",
      options: ["3", "4", "5", "6"],
      correctAnswer: 2,
      hint: "2⁵ = 32",
    },
    {
      question: "¿Cuánto es 7 × 8 - 6 × 7?",
      options: ["7", "8", "10", "14"],
      correctAnswer: 3,
      hint: "56 - 42 = 14",
    },
    {
      question: "¿Qué número elevado al cuadrado da 81?",
      options: ["7", "8", "9", "10"],
      correctAnswer: 2,
      hint: "9² = 81",
    },
    {
      question: "¿Cuánto es 1/3 de 60?",
      options: ["15", "18", "20", "25"],
      correctAnswer: 2,
      hint: "60 ÷ 3 = 20",
    },
    {
      question: "Si a:b = 3:4 y b = 20, ¿cuánto vale a?",
      options: ["12", "13", "15", "16"],
      correctAnswer: 2,
      hint: "a/20 = 3/4",
    },
    {
      question: "¿Cuál es el 125% de 80?",
      options: ["90", "95", "100", "105"],
      correctAnswer: 2,
      hint: "80 × 1.25 = 100",
    },
    {
      question: "¿Cuánto es √(9 + 16)?",
      options: ["5", "6", "7", "8"],
      correctAnswer: 0,
      hint: "√25 = 5",
    },
    {
      question: "Si x/5 = 12/15, ¿cuánto vale x?",
      options: ["3", "4", "5", "6"],
      correctAnswer: 1,
      hint: "Simplifica 12/15 = 4/5",
    },
    {
      question: "¿Cuánto es 2.5 × 4?",
      options: ["9", "9.5", "10", "10.5"],
      correctAnswer: 2,
      hint: "2.5 × 4 = 10",
    },
    {
      question: "¿Cuál es el inverso multiplicativo de 1/4?",
      options: ["1", "2", "4", "-4"],
      correctAnswer: 2,
      hint: "1/(1/4) = 4",
    },
    {
      question: "¿Cuánto es (2⁴) × (2²)?",
      options: ["32", "48", "64", "128"],
      correctAnswer: 2,
      hint: "2⁶ = 64 (suma los exponentes)",
    },
    {
      question: "¿Cuál es el 33.33% de 90?",
      options: ["25", "28", "30", "33"],
      correctAnswer: 2,
      hint: "Aproximadamente 1/3 de 90",
    },
    {
      question: "Si 4x = 36, ¿cuánto vale 2x?",
      options: ["9", "12", "15", "18"],
      correctAnswer: 3,
      hint: "x = 9, entonces 2x = 18",
    },
    {
      question: "¿Cuánto es (20 - 5) ÷ 3?",
      options: ["3", "4", "5", "6"],
      correctAnswer: 2,
      hint: "15 ÷ 3 = 5",
    },
    {
      question: "¿Qué porcentaje es 45 de 150?",
      options: ["25%", "30%", "33%", "35%"],
      correctAnswer: 1,
      hint: "(45/150) × 100 = 30%",
    },
    {
      question: "¿Cuánto es 5/8 + 1/4?",
      options: ["6/8", "7/8", "3/4", "1"],
      correctAnswer: 1,
      hint: "1/4 = 2/8, entonces 5/8 + 2/8 = 7/8",
    },
    {
      question: "Si n² + n = 20, ¿cuánto vale n?",
      options: ["3", "4", "5", "6"],
      correctAnswer: 1,
      hint: "Prueba valores: 4² + 4 = 20",
    },
    {
      question: "¿Cuánto es 3³ - 2³?",
      options: ["17", "18", "19", "20"],
      correctAnswer: 2,
      hint: "27 - 8 = 19",
    },
    {
      question: "¿Cuál es el menor común múltiplo de 4, 6 y 8?",
      options: ["12", "18", "24", "48"],
      correctAnswer: 2,
      hint: "MCM(4,6,8) = 24",
    },
    {
      question: "Si x + y = 15 y x - y = 5, ¿cuánto vale x?",
      options: ["8", "9", "10", "11"],
      correctAnswer: 2,
      hint: "Suma las ecuaciones: 2x = 20",
    },
    {
      question: "¿Cuánto es 1/2 ÷ 1/4?",
      options: ["1/8", "1/2", "2", "4"],
      correctAnswer: 2,
      hint: "Multiplica por el recíproco: (1/2) × 4 = 2",
    },
    {
      question: "¿Cuál es el número que falta? 2, 4, __, 16, 32",
      options: ["6", "8", "10", "12"],
      correctAnswer: 1,
      hint: "Se multiplica por 2 cada vez",
    },
    {
      question: "¿Cuánto es √(64/16)?",
      options: ["2", "3", "4", "8"],
      correctAnswer: 0,
      hint: "64/16 = 4, √4 = 2",
    },
    {
      question: "Si el triple de un número menos 7 es 14, ¿qué número es?",
      options: ["5", "6", "7", "8"],
      correctAnswer: 2,
      hint: "3x - 7 = 14",
    },
    {
      question: "¿Cuánto es 0.3 + 0.7 + 0.5?",
      options: ["1.3", "1.4", "1.5", "1.6"],
      correctAnswer: 2,
      hint: "Suma directa de decimales",
    },
    {
      question: "¿Cuántas diagonales tiene un cuadrilátero?",
      options: ["1", "2", "3", "4"],
      correctAnswer: 1,
      hint: "Un cuadrado o rectángulo tiene 2 diagonales",
    },
    {
      question: "¿Cuánto es 5! - 4!?",
      options: ["20", "80", "96", "100"],
      correctAnswer: 2,
      hint: "120 - 24 = 96",
    },
    {
      question: "Si 7/x = 14/20, ¿cuánto vale x?",
      options: ["8", "9", "10", "11"],
      correctAnswer: 2,
      hint: "14/20 = 7/10, entonces x = 10",
    },
    {
      question: "¿Cuánto es (10²) / (5²)?",
      options: ["2", "3", "4", "5"],
      correctAnswer: 2,
      hint: "100 / 25 = 4",
    },
    {
      question: "¿Qué número multiplicado por sí mismo da 225?",
      options: ["13", "14", "15", "16"],
      correctAnswer: 2,
      hint: "15² = 225",
    },
  ],
  abstracto: [],
  espacial: [],
}

export function getRandomQuestionsByDifficulty(difficulty: number, count: number): Question[] {
  const mathQuestions = questions.matematica
  const totalQuestions = mathQuestions.length
  const questionsPerDifficulty = Math.ceil(totalQuestions / 4)

  let startIndex = 0
  let endIndex = totalQuestions

  // Dividir en 4 niveles de dificultad
  if (difficulty === 1) {
    startIndex = 0
    endIndex = questionsPerDifficulty
  } else if (difficulty === 2) {
    startIndex = questionsPerDifficulty
    endIndex = questionsPerDifficulty * 2
  } else if (difficulty === 3) {
    startIndex = questionsPerDifficulty * 2
    endIndex = questionsPerDifficulty * 3
  } else if (difficulty === 4) {
    startIndex = questionsPerDifficulty * 3
    endIndex = totalQuestions
  }

  const difficultyQuestions = mathQuestions.slice(startIndex, endIndex)

  // Mezclar y seleccionar preguntas aleatorias
  const shuffled = [...difficultyQuestions].sort(() => Math.random() - 0.5)
  return shuffled.slice(0, Math.min(count, shuffled.length))
}
